import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { leaderboardTable } from "@workspace/db/schema";
import { desc } from "drizzle-orm";
import { GetCharactersResponseItem, GetLeaderboardResponseItem, SubmitScoreBody } from "@workspace/api-zod";
import { z } from "zod/v4";

const router: IRouter = Router();

const CHARACTERS = [
  // ===== CRUSADE — HUMAN =====
  {
    id: "human_warrior",
    name: "Sir Aldric Valorheart",
    race: "Human",
    role: "Warrior",
    lore: "Born in the fortified city of Valorheim, Aldric rose through the ranks of the Crusade militia to become its most decorated champion. Orphaned during the First Grudge War, he was raised by the Temple Knights and forged his first blade at twelve. His unbreakable will and mastery of sword and shield have turned the tide of countless battles against the Legion.",
    hp: 245,
    attack: 23,
    defense: 19,
    speed: 57,
    specialAbility: "Invincibility",
    specialAbilityDescription: "Become immune to all damage for a short duration.",
    weakness: "No ranged attacks",
    faction: "Crusade",
    rarity: "rare",
  },
  {
    id: "human_worg",
    name: "Gareth Moonshadow",
    race: "Human",
    role: "Worg",
    lore: "Once captain of the Crusade rangers, Gareth ventured too deep into the Darkwood seeking a cure for a plague. There, the ancient Wolf Spirit Fenrath chose him as vessel. He returned changed, his eyes gleaming amber in the dark — a simple huntsman transformed when a dire wolf spirit bonded with his soul during a blood moon ritual.",
    hp: 235,
    attack: 22,
    defense: 16,
    speed: 67,
    specialAbility: "Feral Rage",
    specialAbilityDescription: "+30% attack speed and damage for 2 turns.",
    weakness: "No healing spells",
    faction: "Crusade",
    rarity: "rare",
    formModels: { bear: { modelId: 'werewolf_form', unlockLevel: 1 }, raptor: { modelId: 'raptor_form', unlockLevel: 10 }, warbear: { modelId: 'warbear_form', unlockLevel: 20 } },
  },
  {
    id: "human_mage",
    name: "Archmage Elara Brightspire",
    race: "Human",
    role: "Mage",
    lore: "Raised in the Brightspire Academy, Elara discovered she could channel both arcane destruction and divine healing — a gift unseen in centuries. The Consortium fears her power; the Crusade depends on it. She was the youngest scholar ever admitted to the Arcane Consortium.",
    hp: 175,
    attack: 21,
    defense: 9,
    speed: 62,
    specialAbility: "Lightning Chain",
    specialAbilityDescription: "Chain lightning hitting up to 5 targets.",
    weakness: "Very fragile in melee",
    faction: "Crusade",
    rarity: "epic",
  },
  {
    id: "human_ranger",
    name: "Kael Shadowblade",
    race: "Human",
    role: "Ranger",
    lore: "Kael grew up in the slums of Port Grimaldi, learning to survive through cunning and speed. Recruited by the Crusade's covert division, he became their finest scout and assassin. A ghost who moves through shadows — his arrows find their mark before the enemy knows war has begun.",
    hp: 185,
    attack: 22,
    defense: 11,
    speed: 72,
    specialAbility: "Rain of Arrows",
    specialAbilityDescription: "Massive AoE ranged barrage hitting all enemies in target zone.",
    weakness: "Low armor and HP",
    faction: "Crusade",
    rarity: "rare",
  },
  // ===== CRUSADE — BARBARIAN =====
  {
    id: "barbarian_warrior",
    name: "Ulfgar Bonecrusher",
    race: "Barbarian",
    role: "Warrior",
    lore: "Ulfgar earned his title by literally shattering a mountain pass to prevent a Legion invasion, burying an entire army beneath tons of stone. The act cost him his left eye but saved his entire tribe. From the frozen peaks of the Northlands, he descends like an avalanche upon his foes.",
    hp: 255,
    attack: 26,
    defense: 17,
    speed: 58,
    specialAbility: "Avatar Form",
    specialAbilityDescription: "+40% all stats, increased size. Rage damage bonus applies.",
    weakness: "No ranged attacks",
    faction: "Crusade",
    rarity: "rare",
  },
  {
    id: "barbarian_worg",
    name: "Hrothgar Fangborn",
    race: "Barbarian",
    role: "Worg",
    lore: "Born during an eclipse, Hrothgar was left in the woods as an omen of doom. Raised by a great wolf mother, he returned to his tribe as a teenager who could speak with beasts and shift form at will. Now he leads a pack of dire wolves across frozen wastes, hunting Legion scouts with savage precision.",
    hp: 245,
    attack: 25,
    defense: 14,
    speed: 68,
    specialAbility: "Worg Lord",
    specialAbilityDescription: "Ultimate tank form with pack summon. +50% HP, summons dire wolves.",
    weakness: "Form-dependent abilities",
    faction: "Crusade",
    rarity: "epic",
    formModels: { bear: { modelId: 'werewolf_form', unlockLevel: 1 }, raptor: { modelId: 'raptor_form', unlockLevel: 10 }, warbear: { modelId: 'warbear_form', unlockLevel: 20 } },
  },
  {
    id: "barbarian_mage",
    name: "Volka Stormborn",
    race: "Barbarian",
    role: "Mage",
    lore: "During a deadly blizzard that buried her village, young Volka discovered she could command the storm itself. The tribal elders named her Stormborn and sent her south to aid the Crusade. Northern shamans channel magic through primal fury — Volka commands blizzards and lightning fueled by raw northern rage.",
    hp: 185,
    attack: 24,
    defense: 7,
    speed: 63,
    specialAbility: "Fireball",
    specialAbilityDescription: "AoE elemental storm damage. Rage bonus applies to spell power.",
    weakness: "Very fragile in melee",
    faction: "Crusade",
    rarity: "epic",
  },
  {
    id: "barbarian_ranger",
    name: "Svala Windrider",
    race: "Barbarian",
    role: "Ranger",
    lore: "Svala was the youngest hunter to ever complete the Trial of the Winter Hunt, tracking and slaying a frost drake alone at age fourteen. She tracks across frozen tundra, through blinding snowstorms, reading the land like an open book. Her arrows are tipped with the venom of ice serpents.",
    hp: 195,
    attack: 25,
    defense: 9,
    speed: 73,
    specialAbility: "Rain of Arrows",
    specialAbilityDescription: "Massive AoE ranged barrage. Rage bonus applies when below 50% HP.",
    weakness: "Low armor and HP",
    faction: "Crusade",
    rarity: "rare",
  },
  // ===== FABLED — DWARF =====
  {
    id: "dwarf_warrior",
    name: "Thane Ironshield",
    race: "Dwarf",
    role: "Warrior",
    lore: "Thane Ironshield is the 47th guardian of the Deep Gate, an unbroken lineage stretching back to the founding of Stonehold. His enchanted shield, Aegis of Ancestors, was forged from the heart of the mountain itself and has never been pierced. When the Grudge Wars began, he sealed the lower mines and marched to war.",
    hp: 260,
    attack: 24,
    defense: 23,
    speed: 52,
    specialAbility: "Invincibility",
    specialAbilityDescription: "Complete damage immunity. Stoneborn +20% Defense stacks on top.",
    weakness: "Very slow movement",
    faction: "Fabled",
    rarity: "epic",
  },
  {
    id: "dwarf_worg",
    name: "Bromm Earthshaker",
    race: "Dwarf",
    role: "Worg",
    lore: "Bromm was a miner who broke through into a sealed cavern containing a primordial earth spirit. The merging nearly killed him but left him able to transform into a creature of rock and fury. By freeing an ancient bear spirit imprisoned in crystal, the spirit merged with his dwarven soul — creating a shapeshifter of living stone.",
    hp: 250,
    attack: 23,
    defense: 20,
    speed: 57,
    specialAbility: "Bear Form",
    specialAbilityDescription: "+50% defense, +30% max HP. Stoneborn defense stacks — virtually unstoppable.",
    weakness: "Extremely slow in all forms",
    faction: "Fabled",
    rarity: "legendary",
    formModels: { bear: { modelId: 'werewolf_form', unlockLevel: 1 }, raptor: { modelId: 'raptor_form', unlockLevel: 10 }, warbear: { modelId: 'warbear_form', unlockLevel: 20 } },
  },
  {
    id: "dwarf_mage",
    name: "Runa Forgekeeper",
    race: "Dwarf",
    role: "Mage",
    lore: "Last of the Forgekeeper bloodline, Runa carries the knowledge of runic magic that predates the Grudge Wars. Her forge-spells burn hotter than dragonfire and her rune-shields are nigh unbreakable. Dwarven magic is not the flashy arcana of elves or humans — it is the deep magic of rune and forge.",
    hp: 190,
    attack: 22,
    defense: 13,
    speed: 52,
    specialAbility: "Mana Shield",
    specialAbilityDescription: "Passive runic barrier. Stoneborn makes her tankier than other mages.",
    weakness: "Slow movement",
    faction: "Fabled",
    rarity: "epic",
  },
  {
    id: "dwarf_ranger",
    name: "Durin Tunnelwatcher",
    race: "Dwarf",
    role: "Ranger",
    lore: "Durin lost his squad to a cave-in during a tunnel patrol. Alone in the dark for thirty days, he learned to navigate by echo and smell. He emerged transformed, able to fight in total darkness. Not all dwarves fight on the front line — Durin patrols the endless tunnels, his crossbow picking off threats in the dark.",
    hp: 200,
    attack: 23,
    defense: 15,
    speed: 62,
    specialAbility: "Precision",
    specialAbilityDescription: "Passive enhanced accuracy. Armor-piercing crossbow bolts ignore partial defense.",
    weakness: "Less range than elf rangers",
    faction: "Fabled",
    rarity: "rare",
  },
  // ===== FABLED — ELF =====
  {
    id: "elf_warrior",
    name: "Thalion Bladedancer",
    race: "Elf",
    role: "Warrior",
    lore: "Trained in the Moonblade Academy for three centuries, Thalion mastered every weapon form before settling on the twin curved blades that earned him his title. Elven warriors do not rely on brute force — Thalion's blade moves like water, each stroke a masterwork of precision against opponents twice his size.",
    hp: 230,
    attack: 22,
    defense: 16,
    speed: 65,
    specialAbility: "Damage Surge",
    specialAbilityDescription: "Blade dance combo +25% ATK. Keen Senses boost accuracy.",
    weakness: "Lower HP than other warriors",
    faction: "Fabled",
    rarity: "rare",
  },
  {
    id: "elf_worg",
    name: "Sylara Wildheart",
    race: "Elf",
    role: "Worg",
    lore: "When the Darkwood began to wither from Legion corruption, Sylara performed the ancient Rite of Binding, merging her soul with the forest's guardian spirit. Last of the Wildheart druids, she channels the spirits of ancient beasts through elven magic. Now she IS the forest's wrath.",
    hp: 220,
    attack: 21,
    defense: 13,
    speed: 70,
    specialAbility: "Worg Lord",
    specialAbilityDescription: "Ancient forest guardian form. Extra mana enables more transformations.",
    weakness: "Fragile base form",
    faction: "Fabled",
    rarity: "legendary",
    formModels: { bear: { modelId: 'werewolf_form', unlockLevel: 1 }, raptor: { modelId: 'raptor_form', unlockLevel: 10 }, warbear: { modelId: 'warbear_form', unlockLevel: 20 } },
  },
  {
    id: "elf_mage",
    name: "Lyra Stormweaver",
    race: "Elf",
    role: "Mage",
    lore: "Lyra spent four hundred years studying in the Crystal Spire before the Grudge Wars forced her into battle. Her mastery of all eight schools of magic makes her the most versatile caster alive. Elven mages are the most powerful spellcasters in all the realms — Lyra channels the raw essence of the ley lines.",
    hp: 160,
    attack: 20,
    defense: 6,
    speed: 65,
    specialAbility: "Lightning Chain",
    specialAbilityDescription: "Storm magic chaining through 5 targets. Arcane Affinity grants +10% mana.",
    weakness: "Extremely fragile",
    faction: "Fabled",
    rarity: "legendary",
  },
  {
    id: "elf_ranger",
    name: "Aelindra Swiftbow",
    race: "Elf",
    role: "Ranger",
    lore: "Captain of the Silverglade Sentinels for two centuries, Aelindra has defended the borders of the Fabled lands against every threat. The greatest archer to ever live, she can split an arrow at three hundred paces while riding at full gallop. Her elven eyes miss nothing.",
    hp: 170,
    attack: 21,
    defense: 8,
    speed: 75,
    specialAbility: "Rain of Arrows",
    specialAbilityDescription: "Arcane arrow storm. Keen Senses and Arcane Affinity boost accuracy and power.",
    weakness: "Very fragile",
    faction: "Fabled",
    rarity: "epic",
  },
  // ===== LEGION — ORC =====
  {
    id: "orc_warrior",
    name: "Grommash Ironjaw",
    race: "Orc",
    role: "Warrior",
    lore: "Born during a blood eclipse, Grommash was destined for war. At age six he killed his first opponent in the fighting pits. By twenty he had united the warring orc clans under one banner — The Legion. His massive cleaver has carved a path of destruction across three continents.",
    hp: 250,
    attack: 27,
    defense: 19,
    speed: 57,
    specialAbility: "Avatar Form",
    specialAbilityDescription: "+40% all stats, increased size. Bloodrage bonus: +20% damage below 50% HP.",
    weakness: "No ranged attacks",
    faction: "Legion",
    rarity: "epic",
  },
  {
    id: "orc_worg",
    name: "Fenris Bloodfang",
    race: "Orc",
    role: "Worg",
    lore: "The fiercest shapeshifter the Legion has ever produced. Fenris earned dominance by defeating every alpha challenger in the wilds. His Bloodrage synergy with beast forms makes him a terrifying force — when wounded, he becomes more dangerous, not less.",
    hp: 240,
    attack: 26,
    defense: 16,
    speed: 67,
    specialAbility: "Feral Rage",
    specialAbilityDescription: "+30% attack speed and damage. Bloodrage adds +20% more when below 50% HP.",
    weakness: "No healing spells",
    faction: "Legion",
    rarity: "legendary",
    formModels: { bear: { modelId: 'werewolf_form', unlockLevel: 1 }, raptor: { modelId: 'raptor_form', unlockLevel: 10 }, warbear: { modelId: 'warbear_form', unlockLevel: 20 } },
  },
  {
    id: "orc_mage",
    name: "Zul'jin the Hexmaster",
    race: "Orc",
    role: "Mage",
    lore: "Zul'jin pried the secrets of blood sorcery from a dying shaman at spearpoint and spent twenty years perfecting them. He carries a war-totem for enemies too close to hex. His blood magic is fueled by the life force of his foes — the more they bleed, the more he feeds.",
    hp: 180,
    attack: 25,
    defense: 9,
    speed: 62,
    specialAbility: "Fireball",
    specialAbilityDescription: "AoE blood-fire explosion. Bloodrage applies +20% spell power when below 50% HP.",
    weakness: "Low physical defense",
    faction: "Legion",
    rarity: "epic",
  },
  {
    id: "orc_ranger",
    name: "Razak Deadeye",
    race: "Orc",
    role: "Ranger",
    lore: "Every head on Razak's wall was once the strongest in its land. The Legion's premier trophy hunter, Razak earned his name by tracking and killing a Crusade general through hostile territory for three weeks straight. His marksmanship is matched only by his patience.",
    hp: 190,
    attack: 26,
    defense: 11,
    speed: 72,
    specialAbility: "Power Shot",
    specialAbilityDescription: "High damage ranged attack at 2x damage. Bloodrage boosts damage when low HP.",
    weakness: "Weak in prolonged melee",
    faction: "Legion",
    rarity: "rare",
  },
  // ===== LEGION — UNDEAD =====
  {
    id: "undead_warrior",
    name: "Lord Malachar",
    race: "Undead",
    role: "Warrior",
    lore: "Lord Malachar once ruled a kingdom that no longer exists. When his city fell, he refused to accept death — binding his soul to his armor through a forbidden pact with the void. Now he marches for the Legion, a deathless knight who has outlasted every war he ever fought in.",
    hp: 265,
    attack: 23,
    defense: 20,
    speed: 52,
    specialAbility: "Guardian's Aura",
    specialAbilityDescription: "+15% defense to all nearby allies. Undead resilience stacks with armor.",
    weakness: "Slow movement",
    faction: "Legion",
    rarity: "epic",
  },
  {
    id: "undead_worg",
    name: "The Ghoulfather",
    race: "Undead",
    role: "Worg",
    lore: "No one knows what The Ghoulfather was in life. In death, he is something vast and terrible — a shambling abomination that absorbs the essence of those it consumes, shifting form with each kill. The Legion uses him like a siege weapon: point, release, collect the remains.",
    hp: 255,
    attack: 22,
    defense: 17,
    speed: 62,
    specialAbility: "Bear Form",
    specialAbilityDescription: "+50% defense, +30% max HP. Undead resilience adds +25 HP baseline.",
    weakness: "No healing spells",
    faction: "Legion",
    rarity: "legendary",
    formModels: { bear: { modelId: 'werewolf_form', unlockLevel: 1 }, raptor: { modelId: 'raptor_form', unlockLevel: 10 }, warbear: { modelId: 'warbear_form', unlockLevel: 20 } },
  },
  {
    id: "undead_mage",
    name: "Necromancer Vexis",
    race: "Undead",
    role: "Mage",
    lore: "Death is not the end for Vexis — it was the beginning. Once a court physician who discovered the secret of soul-binding, Vexis was executed for heresy and rose three days later with full mastery of the dark arts. He harvests souls on the battlefield to fuel spells that make the living envy the dead.",
    hp: 195,
    attack: 21,
    defense: 10,
    speed: 57,
    specialAbility: "Mana Shield",
    specialAbilityDescription: "Soul-barrier from harvested mana. Undead trait adds +5 MP baseline.",
    weakness: "Low physical defense",
    faction: "Legion",
    rarity: "epic",
  },
  {
    id: "undead_ranger",
    name: "Shade Whisper",
    race: "Undead",
    role: "Ranger",
    lore: "Shade Whisper was an assassin in life who was betrayed and buried in an unmarked grave. She returned as something that remembers every face. Her spectral arrows bypass conventional armor, and she moves through shadow like she was born in it — because, in death, she was.",
    hp: 205,
    attack: 22,
    defense: 12,
    speed: 67,
    specialAbility: "Precision",
    specialAbilityDescription: "Spectral sight passive accuracy. Phantom arrows bypass partial defense.",
    weakness: "Weak in prolonged melee",
    faction: "Legion",
    rarity: "rare",
  },
  // ===== PIRATES — SECRET HEROES =====
  {
    id: "pirate_king",
    name: "Racalvin the Pirate King",
    race: "Barbarian",
    role: "Ranger",
    lore: "The Scourge of the Seven Seas. Racalvin commands The Grudge — the most feared warship ever built — and answers to no god, no king, and no grudge he hasn't collected on. A Legendary barbarian ranger whose Storm of Arrows has sunk more ships than any storm the ocean ever made.",
    hp: 225,
    attack: 30,
    defense: 9,
    speed: 78,
    specialAbility: "Storm of Arrows",
    specialAbilityDescription: "Legendary unique ultimate — a hurricane barrage of enchanted bolts hitting all enemies on the field.",
    weakness: "Light armor",
    faction: "Pirates",
    rarity: "legendary",
  },
  {
    id: "sky_captain",
    name: "Cpt. John Wayne",
    race: "Human",
    role: "Warrior",
    lore: "The first captain of Racalvin's crew and the first man in history to pilot a flying machine. A hardened soldier turned sky-pirate, John Wayne traded his medals for a compass and never looked back. His ironclad nerve earned him command of the skies. They say he once flew through a god-storm and came out the other side laughing.",
    hp: 240,
    attack: 30,
    defense: 18,
    speed: 60,
    specialAbility: "Skyfire Barrage",
    specialAbilityDescription: "Legendary unique ultimate — aerial bombing run dealing massive AoE damage from above.",
    weakness: "Ground-based weakness",
    faction: "Pirates",
    rarity: "legendary",
  },
  {
    id: "faith_barrier",
    name: "Scourge FaithBarrier",
    race: "Barbarian",
    role: "Warrior",
    lore: "The oldest blade in Racalvin's crew and the only living soul who has stood at the edge of the Creation Storms and lived to walk into the End Falls. FaithBarrier does not speak of what he saw. He does not need to. The silence before his strike carries the weight of both.",
    hp: 270,
    attack: 33,
    defense: 26,
    speed: 44,
    specialAbility: "Both Shores",
    specialAbilityDescription: "Legendary unique ultimate — FaithBarrier channels the raw force of Creation and End simultaneously, unleashing a shockwave that shatters armor and cannot be blocked or evaded.",
    weakness: "Arcane sorcery",
    faction: "Pirates",
    rarity: "legendary",
  },
];

router.get("/characters", (_req, res) => {
  const characters = CHARACTERS.map((c) => GetCharactersResponseItem.parse(c));
  res.json(characters);
});

router.get("/leaderboard", async (_req, res) => {
  const entries = await db
    .select()
    .from(leaderboardTable)
    .orderBy(desc(leaderboardTable.score))
    .limit(20);

  const result = entries.map((e) =>
    GetLeaderboardResponseItem.parse({
      id: e.id,
      playerName: e.playerName,
      score: e.score,
      wins: e.wins,
      losses: e.losses,
      characterUsed: e.characterUsed,
      createdAt: e.createdAt.toISOString(),
    })
  );
  res.json(result);
});

router.post("/scores", async (req, res) => {
  const body = SubmitScoreBody.parse(req.body);
  const [entry] = await db
    .insert(leaderboardTable)
    .values({
      playerName: body.playerName,
      score: body.score,
      wins: body.wins,
      losses: body.losses,
      characterUsed: body.characterUsed,
    })
    .returning();

  const result = GetLeaderboardResponseItem.parse({
    id: entry.id,
    playerName: entry.playerName,
    score: entry.score,
    wins: entry.wins,
    losses: entry.losses,
    characterUsed: entry.characterUsed,
    createdAt: entry.createdAt.toISOString(),
  });
  res.status(201).json(result);
});

export default router;
